# Generated by Django 5.1.2 on 2024-10-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0002_product_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderReport',
        ),
    ]
