# Generated by Django 5.1.2 on 2024-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0004_remove_supplier_product_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
