# Generated by Django 5.1.2 on 2024-12-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0009_remove_inventorymovement_is_active_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expenses_date',
            field=models.DateTimeField(auto_now_add=True, default="2024-11-28"),
            preserve_default=False,
        ),
    ]
